### ISSUE TITLE
Where is your python Library for apds9960

### ISSUE THREAD

**Issue by alokm014** [liske/python-apds9960#4]
Where is your python Library for apds9960 and how to install it in raspbery pi 3 model b+
Thank you in advance

**Comment by liske** [comment]
It is currently available within this repository and you need to put the `adps9960/` somewhere in your python module path (i.e. next to your source file).

**Comment by alokm014** [comment]
Than you
with the help of your code i made a gesture controlled neopixels led lamp

**Comment by liske** [comment]
I've uploaded it to [PyPi](https://pypi.org/project/apds9960/) so you could now use `pip install apds9960` to install this library.
