### ISSUE TITLE
Enabling both proximity and gesture

### ISSUE THREAD

**Issue by Psychokiller1888** [liske/python-apds9960#6]
Trying to enable proximity and gesture sensors ends in a weird behavior for the proximity sensor that returns weird values

BTW, thank you so much for this library!

**Comment by montarion** [comment]
I realize it's been a while, but this works perfectly fine now, when combined with asyncio

**Comment by Psychokiller1888** [comment]
yeah, feels more like topic necromancy 3.5 years later.... Sry, can't test, not using this library or apds9960 anymore since 2+ years
